GET http://localhost:3000/users



####

POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Orlaith",
    "password": "yess"
}

####
POST http://localhost:5000/signup
Content-Type: application/json

{
    "uname":"aidan1",
    "pass": "fuwbfuwbfuwb"
}


